version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: stock
      POSTGRES_PASSWORD: stock
      POSTGRES_DB: stocktracker
    ports:
      - "5432:5432"